---
title: "Modeling Graduate Outcomes Using National Student Clearinghouse Data"
description: "Higher Education Power BI User Group"
location: "YouTube"
date: "Sep 20, 2023"
format: html
about: 
  id: hero-heading
  template: solana
---

### Abstract

Institutional Research and Technology & Innovation collaborated to create a Power BI report on 
additional education graduates pursue after completing their degree. Multiple faculty requests to IR for 
post-graduation educational pursuits of departmental majors indicated the need for this information. 
Additional uses of the report and these data for other campus departments were identified. This session 
will share the process commencing with requesting data from the National Student Clearinghouse 
through data cleaning, model development, and creation of the final report. Beyond the development 
process, the presentation will include a demonstration of the report features and a discussion of the next 
steps for maintaining and updating the report.

<iframe width="560" height="315" src="https://www.youtube.com/embed/by7plLfKQfU?si=vt9HSettyY3Nglb_" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
